### ISSUE TITLE
Clarification needed on subgraph naming and labeling for different environments

### ISSUE THREAD

**Issue by oerhahon** [wundergraph/cosmo#98]
Hi, 
I am currently playing with the federated graph system and trying to understand how to organize multiple projects and environments.

From the documentation, I understand you can have multiple subgraphs with different environments (dev or prod), but it is not working as I expected.

Scenario:
I have a Federated Graph called Animal with two subgraphs (Cat and Dog). Both of these subgraphs are labeled env=development and I want to promote these in a production environment.

Issue:
I attempted to create a new Federated Graph named Animal-Prod labeled env=production. However, I encountered an issue where I couldn't create subgraphs under Animal-Prod with the same names (Cat and Dog) but with the label env=production.

Questions:
1. Is it a system constraint that prevents creating subgraphs with the same name across different federated graphs, even if they have distinct labels? is the intention to have Cat-dev and Cat-prod
2. What is the recommended approach for promoting subgraphs from a development environment to production, ensuring that both versions coexist? 

Any guidance or clarification on this would be greatly appreciated.

**Comment by thisisnithin** [comment]
Hello @oerhahon. 
1. You are correct as in we check that subgraphs have a unique name despite having different labels. Since we work with labels which canbe anything given the context we do not have a concept of promoting a graph.
2. Since you want both versions to coexist, the recommended approach would be to have subgraphs with different names and labels.

**Comment by oerhahon** [comment]
Thanks for the clarification.
